export const GAME_CONSTANTS = {
  BALL_SIZE: 20,
  BAT_WIDTH: 20,
  BAT_HEIGHT: 150,
  BAT_INDENT: 6,
  DEFAULT_X_SPEED: 3,
  DEFAULT_Y_SPEED: 2,
  BAT_SPEED: 7,
  SPEED_INCREASE_INTERVAL: 10,
  MAX_SPEED_INCREASES: 4,
} as const;
